import { createContext } from 'react';

const articleData = [
  {
    id: 1,
    title: 'The Future of Artificial Intelligence',
    body: 'Artificial Intelligence is rapidly evolving, impacting everything from healthcare to transportation. Experts predict that AI will soon be able to perform complex tasks that currently require human intuition.',
    author: 'John Doe',
    category: 'Technology',
    image: 'https://picsum.photos/seed/ai/800/450',
  },
  {
    id: 2,
    title: 'Top 10 Travel Destinations for 2026',
    body: 'From the serene beaches of Bali to the bustling streets of Tokyo, 2026 is shaping up to be a year of exploration. Travelers are now seeking more sustainable and eco-friendly destinations.',
    author: 'Sarah Smith',
    category: 'Travel',
    image: 'https://picsum.photos/seed/travel/800/450',
  },
  {
    id: 3,
    title: 'The Importance of Mental Health',
    body: "In today's fast-paced world, maintaining mental health is as crucial as physical fitness. Simple practices like mindfulness and regular breaks can significantly improve your quality of life.",
    author: 'Dr. Emily Brown',
    category: 'Health',
    image: 'https://picsum.photos/seed/health/800/450',
  },
  {
    id: 4,
    title: 'Sustainable Living: Easy Tips for Beginners',
    body: "Reducing your carbon footprint doesn't have to be difficult. Start with small steps like using reusable bags, reducing water waste, and choosing energy-efficient appliances.",
    author: 'Mark Green',
    category: 'Environment',
    image: 'https://picsum.photos/seed/eco/800/450',
  },
  {
    id: 5,
    title: 'The Evolution of Modern Architecture',
    body: "Modern architecture is no longer just about aesthetics; it's about functionality and integration with nature. Skyscrapers are now being designed with vertical gardens and smart glass technology.",
    author: 'Jane Wilson',
    category: 'Architecture',
    image: 'https://picsum.photos/seed/arch/800/450',
  },
  {
    id: 6,
    title: 'The Rise of Electric Vehicles',
    body: 'Electric vehicles (EVs) are no longer a niche market. Major automakers are shifting their focus to electric power to reduce emissions and embrace a greener future.',
    author: 'Michael Scott',
    category: 'Automotive',
    image: 'https://picsum.photos/seed/ev/800/450',
  },
  {
    id: 7,
    title: 'The Secret to Perfect Coffee',
    body: "Whether it's the beans' origin or the brewing temperature, making the perfect cup of coffee is an art. Experts say 195-205 degrees Fahrenheit is the sweet spot.",
    author: 'Linda Brew',
    category: 'Lifestyle',
    image: 'https://picsum.photos/seed/coffee/800/450',
  },
  {
    id: 8,
    title: 'Cybersecurity in the Modern Age',
    body: 'With more data online than ever, protecting your digital identity is critical. Two-factor authentication and strong, unique passwords are your first line of defense.',
    author: 'Kevin Mitnick',
    category: 'Technology',
    image: 'https://picsum.photos/seed/security/800/450',
  },
  {
    id: 9,
    title: 'Exploring the Deep Ocean',
    body: 'We know more about the surface of Mars than our own ocean floor. New underwater drones are finally revealing the mysterious creatures living in the midnight zone.',
    author: 'James Cameron',
    category: 'Science',
    image: 'https://picsum.photos/seed/ocean/800/450',
  },
  {
    id: 10,
    title: 'The Benefits of Indoor Gardening',
    body: 'Bringing plants indoors does more than just decorate your home. They purify the air, reduce stress levels, and can even boost your productivity.',
    author: 'Rose Gardener',
    category: 'Lifestyle',
    image: 'https://picsum.photos/seed/plants/800/450',
  },
  {
    id: 11,
    title: 'The Impact of Remote Work',
    body: 'Remote work has changed the global economy forever. While it offers flexibility, it also presents challenges like maintaining work-life balance and team cohesion.',
    author: 'Dwight Schrute',
    category: 'Business',
    image: 'https://picsum.photos/seed/remote/800/450',
  },
  {
    id: 12,
    title: 'Ancient Wonders: The Pyramids',
    body: 'The Pyramids of Giza remain one of the greatest mysteries of engineering. How ancient civilizations moved massive stones with such precision is still debated today.',
    author: 'Zahi Hawass',
    category: 'History',
    image: 'https://picsum.photos/seed/pyramids/800/450',
  },
  {
    id: 13,
    title: 'Healthy Eating on a Budget',
    body: "You don't need to spend a fortune to eat well. Buying seasonal produce and planning your meals ahead of time can save you money and keep you healthy.",
    author: 'Chef Ramsey',
    category: 'Health',
    image: 'https://picsum.photos/seed/food/800/450',
  },
  {
    id: 14,
    title: 'The Future of Space Tourism',
    body: 'Space is becoming accessible to more than just astronauts. Companies like SpaceX and Blue Origin are making civilian space flight a reality in our lifetime.',
    author: 'Elon Musk',
    category: 'Science',
    image: 'https://picsum.photos/seed/space/800/450',
  },
  {
    id: 15,
    title: 'Learning a New Language Fast',
    body: 'Immersion is the key to language learning. Watching movies, listening to music, and speaking with natives can accelerate your progress significantly.',
    author: 'Polyglot Paul',
    category: 'Education',
    image: 'https://picsum.photos/seed/language/800/450',
  },
  {
    id: 16,
    title: 'The Philosophy of Minimalism',
    body: "Minimalism is about more than just owning fewer things. It's about finding freedom from the passion to possess and focusing on what truly matters in life.",
    author: 'Leo Babauta',
    category: 'Lifestyle',
    image: 'https://picsum.photos/seed/minimal/800/450',
  },
  {
    id: 17,
    title: 'Quantum Computing Explained',
    body: "Unlike classical computers, quantum computers use qubits which can exist in multiple states at once. This allows them to solve problems that are impossible for today's PCs.",
    author: 'Richard Feynman',
    category: 'Technology',
    image: 'https://picsum.photos/seed/quantum/800/450',
  },
  {
    id: 18,
    title: 'Yoga for Physical and Mental Strength',
    body: "Yoga combines physical postures, breathing techniques, and meditation to promote physical strength and mental clarity. It's a practice for both body and soul.",
    author: 'Namaste Nina',
    category: 'Health',
    image: 'https://picsum.photos/seed/yoga/800/450',
  },
  {
    id: 19,
    title: 'The Evolution of Video Games',
    body: 'From 8-bit pixels to photorealistic VR experiences, video games have come a long way. They are now a major form of cultural expression and competitive sport.',
    author: 'Gamer One',
    category: 'Entertainment',
    image: 'https://picsum.photos/seed/gaming/800/450',
  },
  {
    id: 20,
    title: 'Urban Farming: Growing in Cities',
    body: 'Urban farming is the practice of cultivating food in a city. Rooftop gardens and vertical farms are helping cities become more self-sufficient and green.',
    author: 'Sky Farmer',
    category: 'Environment',
    image: 'https://picsum.photos/seed/urban/800/450',
  },
];

export const ArticleContext = createContext(articleData);
